# Generated by Django 4.1.13 on 2024-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='FlightDate',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
