# Generated by Django 4.1.13 on 2024-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0002_flight_flightdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='FlightDate',
            field=models.DateField(null='true'),
        ),
    ]
