# Generated by Django 4.1.13 on 2024-03-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_alter_flight_flightdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='FlightDate',
        ),
    ]
