# Generated by Django 4.1.13 on 2024-04-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
