# Generated by Django 5.0.4 on 2024-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('boarding', models.CharField(max_length=100)),
                ('persons', models.CharField(max_length=100)),
                ('luggage', models.CharField(max_length=100)),
                ('fromdate', models.CharField(max_length=100)),
                ('todate', models.CharField(max_length=100)),
            ],
        ),
    ]
