# Generated by Django 5.0.1 on 2024-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
