# Generated by Django 4.1.13 on 2024-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('boardingpoint', models.CharField(max_length=100)),
                ('numberofpersons', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
        ),
    ]
