# Generated by Django 5.0.1 on 2024-02-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
