# Generated by Django 4.1.13 on 2024-04-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='ChillMODEL',
        ),
    ]
