# Generated by Django 5.0.1 on 2024-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
