# Generated by Django 5.0.2 on 2024-02-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_regis_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regis',
            name='phonenumber',
        ),
    ]
