# Generated by Django 5.0.2 on 2024-02-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_regis_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='regis',
            name='phonenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
