# Generated by Django 5.0.2 on 2024-02-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_regis_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sankar',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'Sankar',
            },
        ),
        migrations.DeleteModel(
            name='Regis',
        ),
    ]
