# Generated by Django 5.0.1 on 2024-02-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sankar_delete_regis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sankar',
            old_name='name',
            new_name='FirstName',
        ),
    ]
